name: 'Update readme'

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  lint:
    name: README Stats
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        node: ['lts/*']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          standalone: true

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate README.md
        run: 'pnpm run start'

      - name: Save changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name k4itrunBot
          git config user.email 153697070+k4itrunBot@users.noreply.github.com
          git add .
          git commit -m "chore(bot): Update readme"
          git push -f
          fi
