name: 'Update readme'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  lint:
    name: README Profile
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        node: ['lts/*']
    permissions:
      contents: write # Allows writing to the repository (necessary for pushing tags and changes)
      issues: write # Allows creating and modifying issues
      pull-requests: write # Allows creating and modifying pull requests
      id-token: write # Grants access to GitHub Actions ID token
      actions: write # Allows execution of custom GitHub Actions
      packages: write # Allows publishing packages to GitHub Packages (if applicable)
      deployments: write # Allows deployment of releases (if deploying automatically)
      discussions: write # Allows interacting with GitHub Discussions (if used)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          standalone: true

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate profile README.md
        run: 'pnpm run start'

      - name: Save changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          NAME="k4itrunBot"
          EMAIL_ID="153697070"
          EMAIL_DOMAIN="users.noreply.github.com"
          EMAIL="${EMAIL_ID}+${NAME}@${EMAIL_DOMAIN}"
          TIMESTAMP=$(date +"%a %b %d %H:%M:%S %Y %z" | tr '[:upper:]' '[:lower:]')
          git config --local user.name "$NAME"
          git config --local user.email "$EMAIL"
          git add -A
          git commit -m "chore(bot): update readme - updated at: $TIMESTAMP"
          git push --force
          fi
